version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: diary-db
    restart: always
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: diary_db
    ports:
      - "5432:5432"
